[versions]
agp                      = "8.12.3"
appcompat                = "1.7.1"
coilCompose              = "2.7.0"
composeBom               = "2026.01.01"
coreKtx                  = "1.17.0"
hiltNavigationCompose    = "1.3.0"
kotlin                   = "2.3.0"
composePlugin            = "2.3.0"
hilt                     = "2.58"
kotlinxCoroutinesAndroid = "1.10.2"
ksp                      = "2.3.3"
lifecycleRuntimeKtx      = "2.10.0"
loggingInterceptor       = "5.3.2"
retrofit                 = "3.0.0"
room                     = "2.8.4"
compose                  = "1.9.5"

junit                    = "4.13.2"
junitVersion             = "1.3.0"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library     = { id = "com.android.library", version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose             = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "composePlugin"}
hilt                = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp                 = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
androidx-core-ktx                        = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-appcompat                       = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

androidx-compose-bom                     = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material                = { module = "androidx.compose.material:material" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

androidx-hilt-navigation-compose         = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-lifecycle-runtime-ktx           = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

coil                                     = { module = "io.coil-kt:coil", version.ref = "coilCompose" }
coil-compose                             = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }

hilt-android                             = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler                    = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

kotlinx-coroutines-android               = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }

logging-interceptor                      = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
retrofit                                 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson                           = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

room-runtime                             = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx                                 = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler                            = { module = "androidx.room:room-compiler", version.ref = "room" }

junit                                    = { module = "junit:junit", version.ref = "junit" }
androidx-junit                           = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }


#bomed
#compose-ui                          = { module = "androidx.compose.ui:ui", version.ref = "compose" }
#compose-ui-tooling                  = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
#androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
